const ACTIONS = {
    LOAD_BOOKS: 'LOAD_BOOK',
    FILTER_BOOKS: 'FILTER_BOOKS',
    ADD_TO_CART: 'ADD_TO_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
}

export default ACTIONS;