const ACTIONS = {
    LOAD_BOOKS: 'LOAD_BOOK',
    FILTER_BOOKS: 'FILTER_BOOKS',
    ADD_TO_CART: 'ADD_TO_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
    HANDLE_CART_MODAL: 'HANDLE_CART_MODAL',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY',
    UPDATE_COMMERCIAL_OFFERS: 'UPDATE_COMMERCIAL_OFFERS',
    CHECKOUT: 'CHECKOUT',
    SET_INFO: "SET_INFO",
    REMOVE_INFO: "REMOVE_INFO"
}

export default ACTIONS;